### ISSUE TITLE
Big Cluster "Sampling" on N6P running Android 10

### ISSUE THREAD

**Issue by armyav8tor** [franciscofranco/FK-Kernel-Manager-IssuesAndFeatureRequest#108]
I'm running PixelExperience 10 on my Nexus 6P and FK Kernel Manager reports big cluster as Sampling and never shows the Frequency.  Under Live Monitor, it shows 0% for all CPUs and under CPU STATS, the big cluster seems to be missing a lot of data.  Everything reports fine under EX but I like the FK interface more.  Please let me know if there's something we can do to get it to report correctly, thanks!!

![Screenshot_20190924-114105](https://user-images.githubusercontent.com/15371423/65528596-ada7fc80-dec2-11e9-939b-c242ba8e524d.png)

![Screenshot_20190924-115452](https://user-images.githubusercontent.com/15371423/65528622-bac4eb80-dec2-11e9-81e0-4e3578d1a0af.png)

![Screenshot_20190924-115516](https://user-images.githubusercontent.com/15371423/65528655-c6b0ad80-dec2-11e9-871c-30123e574051.png)

**Comment by franciscofranco** [comment]
Hmm, that happens if the cores are offline. As you see the big cluster freq reports as "offline". Though I see your point, it shouldn't say "Sampling" in there. I'll fire up my N6P and run some tests. Don't expect a fix for the next small release since this requires some time for debugging, but as soon as I figure this out I'll push the fix to the store.

**Comment by franciscofranco** [comment]
Fixed for next release.
