### ISSUE TITLE
Long delay when switching pages

### ISSUE THREAD

**Issue by kdrag0n** [franciscofranco/FK-Kernel-Manager-IssuesAndFeatureRequest#4]
The app feels slow as compared to some other kernel managers when switching pages using the bottom-swipe-up menu. There are three major factors contributing to this issue:
 - Inefficient layouts that are more complex than necessary, thus taking longer to inflate. For example, ConstraintLayouts are often faster than using many nested FrameLayouts, RelativeLayouts, and LinearLayouts. [See this article for why.](https://android-developers.googleblog.com/2017/08/understanding-performance-benefits-of.html)
 - Lack of an animation, making the delay seem longer than it actually is. A loading indicator somewhere on the screen after the menu collapses (the solution employed by EXKM) while the work is taking place would be helpul in mitigating this. Using an AsyncLayoutInflater (if possible) may be necessary to keep the loading indicator animating at 60 fps while the layouts are being inflated in the background.
 - A relatively long menu collapsing animation as compared to the sidebars used by other apps.

Addressing all or some of these should improve the app's UX significantly.

**Comment by franciscofranco** [comment]
An AsyncLayoutInflater doesn't really make much difference, inflating layouts it's pretty trivial and cheap, and the bulk of the work is done in a background thread and posted to the UI thread through a ViewModel.

I don't use RelativeLayouts. They suck and they're slow. More often than not I use FrameLayouts since they're the cheapest ViewGroup, so ConstrainLayout won't really do much for me.

The menu closes as soon as the fragment is created so it doesn't really rely on my own code, rather the framework's factories.
